export { About } from './About'
export { Services } from './Services'
export { Hero } from './Hero'
export { FAQ } from './FAQ'
export { Team } from './Team'
export { Contact } from './Contact'
export { Pricing } from './Pricing'
